name: Python app test with GA

on: [push]

jobs:
  build:
  runs-on: ubuntu-latest
  continue-on-error: true
  strategy:
       fail-fast: false
       matrix:
         # Testing different versions of python
         python-version: [3.7, 3.8, 3.9, 3.10.14 ]         
    steps:
    - uses: actions/checkout@v2
    - name: Set up python
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        python-version: 3.10.14
        experimental: true
        
    - name: Install dependencies
      run: |
        make install
    
    - name: Format code
      run: |
        make format
      
  #  - name: Lint 
  #    run: |
  #      make lint
    
    - name: Test 
      run: |
        make test
    
